name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
      - php-workflows-poc

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: php:8.2-cli-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install

      - name: Compile build
        run: find . -name "*.php" ! -path "./vendor/*" | xargs -n 1 php -l || exit 1

      - name: Run tests
        run: ./vendor/bin/phpunit